select * from FAVORITOS
select * from USERS

--ALTER TABLE FAVORITOS ADD CONSTRAINT PK_FAVORITOS PRIMARY KEY (Id)

--ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (Id)

--ALTER TABLE FAVORITOS ADD CONSTRAINT FK_Favoritos_User FOREIGN KEY (IdUser) REFERENCES USERS(Id)
--ALTER TABLE FAVORITOS ADD CONSTRAINT FK_Favoritos_Articulos FOREIGN KEY (IdArticulo) REFERENCES ARTICULOS(Id)

--ALTER TABLE ARTICULOS ADD CONSTRAINT FK_Articulos_Marcas FOREIGN KEY (IdMarca) REFERENCES MARCAS(Id)

SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_NAME = 'FAVORITOS'